from ErrorAplicacion import ErrorAplicacion
class ExepcionC2(ErrorAplicacion):
    pass